language: node_js
node_js:
  - "6"
before_install:
  - mv build-libs client/node_modules 
  - cd client
before_script:
  - npm install -g bower
  - npm install -g gulp-cli
script: 
  - cd web
  - bower install
  - cd ..
  - gulp
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: builds/web/development
  on:
    branch: master
