language: node_js
node_js:
  - "6"
cache:
  directories:
  - client/node_modules
before_install:
  - cp -avf build-libs/* client/node_modules/ 
  - cd client
before_script:
  - npm install -g bower
  - npm install -g gulp-cli
script: 
  - cd web
  - bower install
  - cd ..
  - gulp
addons:
  apt:
    packages:
      - sshpass
after_success:
  - export SSHPASS=$ONE_COM_SSH
  - sshpass -e rsync --archive --delete --chmod=Du=rwx,go=rx,Fu=rwx,og=rx "client/builds/web/development/" "davidmiles.se@ssh.davidmiles.se:/www/"

