language: node_js
node_js:
  - "6"
cache:
  directories:
  - client/node_modules
before_install:
  - cp -avf build-libs/* client/node_modules/ 
  - cd client
before_script:
  - npm install -g bower
  - npm install -g gulp-cli
script: 
  - cd web
  - bower install
  - cd ..
  - gulp
addons:
  ssh_known_hosts: $SSH_HOST
  apt:
    packages:
      - sshpass
after_success:
  - export SSHPASS=$SSH_PASS
  - sshpass -e rsync --archive --delete --chmod=Du=rwx,go=rx,Fu=rwx,og=rx builds/web/development/ $SSH_USER@$SSH_HOST:/www/

